// TEST for
const EXAMPLE = [
  {
    url: "/catsAvatar/0.jpg", // 暂时先用一下
    title: "Title-1",
    userAvatar: "/static/cats/head/1.png",
    userName: "小王",
    time: "22.12.31",
    like: true,
    height: 2397,
    width: 1600,
  },
  {
    url: "/catsAvatar/5.jpg",
    title: "Title-4",
    userAvatar: "/static/cats/head/4.png",
    userName: "软软!!!",
    time: "23.1.1",
    like: false,
    height: 1080,
    width: 1440,
  },
  {
    url: "/catsAvatar/0.jpg", // 暂时先用一下
    title: "Title-1",
    userAvatar: "/static/cats/head/1.png",
    userName: "小王",
    time: "22.12.31",
    like: true,
    height: 2397,
    width: 1600,
  },
  {
    url: "/catsAvatar/2.jpg",
    title: "默认标题默认标题默认标题默认标题默认标题",
    userAvatar: "/static/cats/head/3.png",
    userName: "张三",
    time: "23.3.5",
    like: true,
    height: 1600,
    width: 2133,
  },
  {
    url: "/catsAvatar/1.jpg",
    title: "Title-2 WHU WHU WHU WHU",
    userAvatar: "/static/cats/head/2.png",
    userName: "李华",
    time: "23.2.14",
    like: false,
    height: 1776,
    width: 1184,
  },
  {
    url: "/catsAvatar/5.jpg",
    title: "Title-4",
    userAvatar: "/static/cats/head/4.png",
    userName: "软软!!!",
    time: "23.1.1",
    like: false,
    height: 1080,
    width: 1440,
  },
  {
    url: "/catsAvatar/2.jpg",
    title: "默认标题默认标题默认标题默认标题默认标题",
    userAvatar: "/static/cats/head/3.png",
    userName: "张三",
    time: "23.3.5",
    like: false,
    height: 1600,
    width: 2133,
  },
];
